# this method parses a gene structure file and returns status of gene prediction (only if done with webscipio)
# @path [String] path to gene structure file
# returns [String] status or "missing" if file does not exist
def get_status_of_gene_structure(path)

	if ! FileTest.file?(path) then 
		# gene structure is missing
		return "missing"
	else
		status = "unknown" # default status
		if File.extname(path) == ".yaml" then 
			# file was generated by Scipio, try to inferr prediction status
			IO.foreach(path) do |line|
				line = line.chomp
				if match_data = line.match(/status: ([\w]+)/) then
					# don't allow arbitrary status messages
					if match_data[1] == "auto" then 
						status = "complete"
					end
					if  match_data[1] == "incomplete" || match_data[1] == "partial" then
						status = match_data[1]
					end
					break
				end
			end
		else
			# file not generated by Scipio, just stick with default status
		end
		return status
	end
end

# this method generated gene structures for _all_ genes specified in list_of_genes_to_process
# @list_of_genes_to_process [Array] Gene names (fasta headers) for which a gene structure should be generated
# @path_to_species_to_fasta [String] Path to file which maps species to gene names (fasta headers)
# @path_to_fasta [String] Path to fasta formatted file (can contain more sequences than listed in path_to_species_to_fasta)
# @output_path [String] Path to location, where generated gene structures should be stored
# returns [Boolean] successfull call of script that generates all gene structures at once (thats unrelated to the status of individual gene structures)
# returns [Array] list of newly generated files in output_path
def generate_gene_structures( list_of_genes_to_process, path_to_species_to_fasta, path_to_fasta, output_path)

	pre_existing_genestructures = Dir.glob( File.join(output_path, "*.*") ).collect{|ele| File.basename(ele)}

	path_to_genes_list = File.join(output_path, "genes_whitelist_#{rand(1000)}.txt")
	IO.write( path_to_genes_list, list_of_genes_to_process.join("\n"), :mode => "w" )

	path_to_genepainter = "/fab8/server/db_scripts/gene_painter_new/gene_painter" # FIXME adjust path to genepainter standalone, best createa an constant with switch for fab8/cymo server
	path_to_yaml_genenerator = File.join( path_to_genepainter, "tools", "generate_yaml_for_multiple_species.rb" )

	is_success = system("ruby #{path_to_yaml_genenerator} -s #{path_to_species_to_fasta} -i #{path_to_fasta} -w #{path_to_genes_list} -p #{output_path}")

	File.delete(path_to_genes_list)

	finally_existing_genestructures = Dir.glob( File.join(output_path, "*.*") ).collect{|ele| File.basename(ele)}
	newly_generated_genestructures = finally_existing_genestructures - pre_existing_genestructures

	return is_success, newly_generated_genestructures
end
